### ISSUE TITLE
Link to go back to spinalcordmri.org from the forum

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordmri/spinalcordmri.github.io#17]
it would be nice if the link shown above would redirect to the spinalcordmri.org website:

![screen shot 2018-09-13 at 14 42 34](https://user-images.githubusercontent.com/2482071/45508693-722d0b00-b763-11e8-87b5-c4228ff17ad6.png)

**Comment by alexfoias** [comment]
Would something like this work ?
![screen shot 2018-09-14 at 12 26 46 pm](https://user-images.githubusercontent.com/12564433/45562833-86cbda80-b819-11e8-8a80-5cbf5a9f5287.png)

I think we should also change the logo to add the name of the site/community.

**Comment by jcohenadad** [comment]
i would rather write something like "Back to spinalcordmri.org"

> I think we should also change the logo to add the name of the site/community.

agreed!

**Comment by alexfoias** [comment]
I made a clone of the default theme with the added link. You can check it here: http://forum.spinalcordmri.org/

**Comment by jcohenadad** [comment]
looks nice! but would it be possible to have the text on the right of the fig (instead of at the top)

**Comment by alexfoias** [comment]
I found another approach. This one adds a button next to search button. We could imagine a rectangular button with the text Back to spinalcordmri.org. 

Which one do you prefer ?

**Comment by jcohenadad** [comment]
ah yeah, that's nice!

**Comment by jcohenadad** [comment]
however, what i would find more intuitive, would be to use the image on the left as a link to spinalcordmri.org (because it has the image of the website), and the home button as the home of the forum (because it is spatially in the section specific to the forum)

**Comment by alexfoias** [comment]
I totally agree with you. I will look into it.

**Comment by alexfoias** [comment]
Give it a try. http://forum.spinalcordmri.org/

I kept the home button to go to the home page of the forum.

**Comment by jcohenadad** [comment]
👍

**Comment by alexfoias** [comment]
The feature was implemented directly on the Discourse admin interface. For future customization go to http://forum.spinalcordmri.org/admin/customize/themes and adapt the implemented components (Head button, Headlink). [Ref.](https://meta.discourse.org/t/add-new-link-on-header-beside-search-icon/48621/17). This issue can be closed.
