### ISSUE TITLE
Embed OSF page within the spinalcordtoolboxmri.org page

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordmri/spinalcordmri.github.io#18]
It would be great if, instead of redirecting to the OSF URL, we would instead embed the OSF page inside the website, so that the user is still within the ecosystem of the website (if he/she wants to surf the website).

**Comment by alexfoias** [comment]
I tried to embed the page using iframe, but I couldn't get it work. I contacted osf support to ask them if they offer the option of embedding the homepage of a project in a normal HTML.

**Comment by alexfoias** [comment]
Unfortunately, embedding is not possible on OSF. Here is their response: 

> This functionality is not possible. What you can do is add a redirect link on your project that directs to the webpage, and then link to your OSF project from the external page. For step-by-step instructions on how to add a redirect link, see our help guide here: http://help.osf.io/m/links_forks/l/767510-add-a-redirect-link

**Comment by jcohenadad** [comment]
too bad, but worth a try :-)
