### ISSUE TITLE
Have written "Spinal Cord MRI - Forum" written on top left of the forum

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordmri/spinalcordmri.github.io#28]
something like that:

![screen shot 2019-01-09 at 11 19 22](https://user-images.githubusercontent.com/2482071/50912695-c5a52200-1400-11e9-9b0e-151b30e189e5.png)

**Comment by alexfoias** [comment]
@jcohenadad could you please let me know if like the font size ? Thank you

**Comment by jcohenadad** [comment]
> could you please let me know if like the font size

sorry i don't get the question

**Comment by alexfoias** [comment]
I added the new logo on http://forum.spinalcordmri.org/
