### ISSUE TITLE
Reorganize display to clarify dates and name of events

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordmri/spinalcordmri.github.io#37]
Currently, the dates placement is a bit confusing: it is not clear if the date for an event is above or below the event:

![Screen Shot 2019-10-02 at 3 23 04 PM](https://user-images.githubusercontent.com/2482071/66075037-a919be80-e528-11e9-9b24-2b226322137e.png)

The template needs to be modify to clarify the display

**Comment by alexfoias** [comment]
@jcohenadad Do you want to put the dates under the event ?

**Comment by jcohenadad** [comment]
> @jcohenadad Do you want to put the dates under the event ?

yes, under the event, and with less space between the event and the date (so there is less confusion about the dates referring to the event above or below)

**Comment by alexfoias** [comment]
How about something like this ? Or do you want a different format for the date? I also addressed #36  

![Screen Shot 2019-10-03 at 12 18 09 PM](https://user-images.githubusercontent.com/12564433/66145032-f012bd00-e5d7-11e9-8cc3-6df0011d2250.png)

**Comment by jcohenadad** [comment]
this is great!!!

**Comment by jcohenadad** [comment]
p.s. the london workshop should **not** be changed to 8th workshop (we already sent the announcement, etc.)

the beijing workshop should be SCT course-- but once you create the branch i will be able to do the modifs

**Comment by alexfoias** [comment]
Fixed in https://github.com/spinalcordmri/spinalcordmri.github.io/pull/41
