### ISSUE TITLE
Add media logo to index page

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordmri/spinalcordmri.github.io#5]
twitter, github, instagram, etc.

**Comment by alexfoias** [comment]
@jcohenadad should we add it in the footer ? what media logo should we add (GH,OSF, Discourse) ?

**Comment by jcohenadad** [comment]
Actually, maybe we don't need to add those media logo. In that case, maybe we can get rid of the white space on the left of the image.

**Comment by alexfoias** [comment]
I think we can close this issue.
