### ISSUE TITLE
Discussion about assets

### ISSUE THREAD

**Issue by alexfoias** [spinalcordmri/spinalcordmri.github.io#54]
I saw that for the latest workshop, some logos are under `/assets/2020-01-20-workshop`. For the previous workshops we save the logos directly under `/assets,` I think out of simplicity in case we want to reuse them. 

@jcohenadad @fprados What do you think about it ?

**Comment by jcohenadad** [comment]
we should not duplicate images under this repos (it adds fat) but instead reuse, and thus put everything under /assets.

**Comment by jcohenadad** [comment]
but it's too late now (fat is already there). to remember for next time

**Comment by fprados** [comment]
Either one way or the other is fine to me. I've started putting all together, but then I realised that we created a folder for a previous event. For this reason, I've changed to folders. But I can move everything to **asset**, it is not difficult.

Have a nice weekend guys!
