### ISSUE TITLE
Link to video only points to day one

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordmri/spinalcordmri.github.io#66]
here: http://www.spinalcordmri.org/2020/01/20/workshop.html#minutes-of-the-meeting

it says: "Recordings of the workshop from both days can be found here. " however, the link only points to day 1

**Comment by jcohenadad** [comment]
Also, i would make a specific section: "Recordings" so we can easily refer with URL

**Comment by alexfoias** [comment]
I think we can point directly to the playlist workshop: https://www.youtube.com/playlist?list=PLJ5-Fnq9XpaW7hLYbQCZaxGAp_iuKUiql

What do you think ? Or you would like a new playlist for that event ?
